### ISSUE TITLE
v4 API errors

### ISSUE THREAD

**Issue by SURViR** [chirpstack/chirpstack-fuota-server#12]
Hi! Documentation of ChirpStack V4 brings me here, but chirpstack-fuota-server doesn't work itch ChirpStack v4 and I can't find easy workaround of this - is there any possibility it will be fixed soon?
Main problem is that Application ID is now UUID and not INT, but when I wanted to fix this many API differences stopped me from making it possible.

**Comment by brocaar** [comment]
I've just updated the master branch with the v4 integration.
