### ISSUE TITLE
FUOTA Server Webinterface not opening

### ISSUE THREAD

**Issue by kannansks** [chirpstack/chirpstack-fuota-server#3]
I was able to start the fuota server once i removed all tls certificates from the as and ns however even though it has started and is active running i cannot open the 10.10.20.61:8090 which is the ip:port of the fuota server
 i have added http integration in my a-s web interface 
![fuota](https://user-images.githubusercontent.com/78213032/110349653-e7d67100-8058-11eb-845d-0ac8489a3d62.PNG)

should i give 8090 or 8070 here??
what am i doing wrong plss help!!

**Comment by symovs** [comment]
@kannansks I think we have to give 8070. 

![image](https://user-images.githubusercontent.com/66220236/111034849-75410900-843d-11eb-923a-767bf58f0b35.png)

But am getting this error in fuota server journals 

@brocaar pls help 

![image](https://user-images.githubusercontent.com/66220236/111034882-a3bee400-843d-11eb-89b0-16cbc0a68212.png)

**Comment by symovs** [comment]
@brocaar the ports are also all open 

![Uploading image.png…]()

**Comment by brocaar** [comment]
> i cannot open the 10.10.20.61:8090 which is the ip:port of the fuota server

The FUOTA server does not have a web-interface. You have to use the gRPC API for this:

https://github.com/brocaar/chirpstack-api/blob/master/protobuf/fuota/fuota.proto#L14

**Comment by symovs** [comment]
> > i cannot open the 10.10.20.61:8090 which is the ip:port of the fuota server
> 
> The FUOTA server does not have a web-interface. You have to use the gRPC API for this:
> 
> https://github.com/brocaar/chirpstack-api/blob/master/protobuf/fuota/fuota.proto#L14

Thanks brocaar. Would it be possible for you to provide a sample web interface also ? Something that would sort of be a reference for custom implementations. We would appreciate this very much

**Comment by kannansks** [comment]
> > > i cannot open the 10.10.20.61:8090 which is the ip:port of the fuota server
> > 
> > 
> > The FUOTA server does not have a web-interface. You have to use the gRPC API for this:
> > https://github.com/brocaar/chirpstack-api/blob/master/protobuf/fuota/fuota.proto#L14
> 
> Thanks brocaar. Would it be possible for you to provide a sample web interface also ? Something that would sort of be a reference for custom implementations. We would appreciate this very much

@brocaar we were testing fuota with ns version 3.10 and as 3.12 and once we updated to latest version fuota has become an issue and being beginners we are finding it difficult to work around it so we would be grateful if u could help us

**Comment by brocaar** [comment]
> Would it be possible for you to provide a sample web interface also ? Something that would sort of be a reference for custom implementations.

Providing a web-interface is not planned. There is an example implementation however for Class-C as a starting point:
https://github.com/chirpstack/chirpstack-fuota-server/blob/master/examples/class_c/main.go
