### ISSUE TITLE
chirpstack-fuota-server installation without docker

### ISSUE THREAD

**Issue by shabaz-git** [chirpstack/chirpstack-fuota-server#5]
Hi,
We are having our chirpstack-gateway-bridge, network-server, application-server and database also present without docker. We struggled a lot to up them to work for regular otaa. Now we thought of enabling fuota and observed that only docker implementation is available. So can you suggest any steps to do without docker.

Thanks

**Comment by brocaar** [comment]
The Docker Compose environment is there to provide you with a ready-to-use development environment for compiling. The resulting binary can be used without issues without depending on Docker. Alternatively, you can setup a local development environment with the same tools as provided by the Compose environment and compile the FUOTA server without using Docker
