### ISSUE TITLE
make: go: Operation not permitted 

### ISSUE THREAD

**Issue by shabaz-git** [chirpstack/chirpstack-fuota-server#6]
Hi,
I am trying to run following command to bring up chirpstack fuota server
 `docker-compose run --rm chirpstack-fuota-server bash`
but it is getting failed with following errors:
```
Step 10/10 : RUN make dev-requirements
 ---> Running in d300d3fb99b5
go install github.com/rakyll/statik
make: go: Operation not permitted
make: *** [Makefile:36: dev-requirements] Error 127
ERROR: Service 'chirpstack-fuota-server' failed to build: The command '/bin/sh -c make dev-requirements' returned a non-zero code: 2
```
I am having `go` with version `go1.15.2.`
Environment variables also look fine.
Even I am able to install individual package using  `go install github.com/rakyll/statik` without any error and able to see package as well.
What might be the cause?
Can anyone help?

Thanks

**Comment by brocaar** [comment]
This looks like an environmental issue (e.g. permissions). I can not reproduce this.
