### ISSUE TITLE
chirpstack-fuota-server_chirpstack-fuota-server_1 exited with code 0

### ISSUE THREAD

**Issue by t0mZ4** [chirpstack/chirpstack-fuota-server#9]
Hi
I cannot get the fuota server to run using docker-compose

i have chirpstack running on the same server
i configure the api token in packaging/files/chirpstack-fuota-server.toml

and I get chirpstack-fuota-server_chirpstack-fuota-server_1 exited with code 0 in the docker-compose logs

not sure what's going on here, am I missing a step? do I need to compile from source first?

**Comment by brocaar** [comment]
The provided Compose environment is for development. Please note that you might not be able to connect between two separate container instances without network configuration between the two.
